# Generated by Django 4.0.2 on 2022-04-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_alter_mobile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='oneplus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='oneplus', max_length=20)),
                ('modelname', models.CharField(max_length=25)),
                ('price', models.IntegerField(default=None)),
                ('discription', models.TextField()),
                ('image', models.ImageField(upload_to='oneplusimages')),
            ],
            options={
                'db_table': 'oneplusmob.',
            },
        ),
    ]
