# Generated by Django 4.0.2 on 2022-04-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_oneplus'),
    ]

    operations = [
        migrations.CreateModel(
            name='redmi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='redmi', max_length=20)),
                ('modelname', models.CharField(max_length=25)),
                ('price', models.IntegerField(default=None)),
                ('discription', models.TextField()),
                ('image', models.ImageField(upload_to='redmimages')),
            ],
            options={
                'db_table': 'redmimob',
            },
        ),
    ]
